# Generated by Django 4.2.6 on 2024-02-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('sname', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('sprincipal', models.CharField(max_length=100)),
                ('slocation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stname', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('stage', models.IntegerField()),
                ('sname', models.CharField(max_length=100)),
            ],
        ),
    ]
